pipeline {
    agent {
      docker {
        image 'python:2.7.16-slim'
      }
    }

    stages {
        stage('build') {
            when {
              changeset '**/vote/**'
            }
            steps {
                dir('vote') {
                  sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test') {
            when {
              changeset '**/vote/**'
            }
            steps {
              dir('vote') {
                sh 'nosetests -v'
              }
            }
        }
    }
    post {
        always {
            echo 'This pipeline is completed now :-)'
        }
    }
}
