pipeline {
    agent none

    stages {
        stage('build') {
            agent {
              docker {
                image 'python:2.7.16-slim'
                args '--user root'
              }
            }
            when {
              changeset '**/vote/**'
            }
            steps {
                dir('vote') {
                  sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test') {
            agent {
              docker {
                image 'python:2.7.16-slim'
                args '--user root'
              }
            }
            when {
              changeset '**/vote/**'
            }
            steps {
              dir('vote') {
                sh 'nosetests -v'
              }
            }
        }

        stage('docker-package') {
            agent any
            when {
               changeset '**/vote/**'
            }
            steps {
               echo 'voter app with docker'
               script {
                 docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
                 def workerImage = docker.build("robrockdataio/vote:v${env.BUILD_ID}","./vote")
                 workerImage.push()
                 workerImage.push("${env.BRANCH_NAME}")
               }
            }
          }
        }


    }
    post {
        always {
            echo 'This pipeline voter is completed now ! >-) :-) >-)'
        }
    }
}
