pipeline {
    agent any

    tools{
      maven 'Maven 3.6.1'
    }


    stages {
        stage('build') {
            steps {
                echo 'Compile'
                dir('worker') {
                  sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
              dir('worker') {
                echo 'mvn clean test'
              }
            }
        }
        stage('package') {

            steps {
              dir('worker') {
                echo 'mvn package -DskipTess'
            }
          }
        }

    }
    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'This pipeline is completed now'
        }
    }
}
