pipeline {
    agent none 


    stages {
        stage('build') {
            agent{
		docker {
			image 'maven:3.6.1-jdk-8-alpine'
			args '-v $HOME/.m2:/root/.m2'
		}
	    } 
            when {
              changeset '**/worker/**'
            }
            steps {
                dir('worker') {
                  sh 'mvn compile'
                }
            }
        }
        stage('test') {
             agent{
	       docker {
			image 'maven:3.6.1-jdk-8-alpine'
			args '-v $HOME/.m2:/root/.m2'
		}
	    }           
	    when {
              changeset '**/worker/**'
            }
            steps {
              dir('worker') {
                sh 'mvn clean test'
              }
            }
        }
        stage('package') {
           agent{
		docker {
			image 'maven:3.6.1-jdk-8-alpine'
			args '-v $HOME/.m2:/root/.m2'
		}
	    }
	     when {
              branch 'master'
              changeset '**/worker/**'
            }
            steps {
              dir('worker') {
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
          }
        }

        stage('docker-package') {
	    agent any
            when {
              changeset '**/worker/**'
            }
            steps {
	      echo 'worker app with docker'
              script {
		docker.withRegistry('https://index.docker.io/v1', 'dockerlogin'){
			def workerImage = docker.build("robrockdataio/worker:v${env.BUILD_ID}","./worker")
			workerImage.push()
		}
	      }
          }
        }
 

    }

    post {
        always {
            echo 'This pipeline is completed now dockerized >-)'
        }
    }
}
